astro_task_store/urls.py
from django.contrib import admin
from django.urls import path, include

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('admin/', admin.site.urls),
    path('problems/', include('problems.urls')),
    path('command/', views.command),
    path('profile/', views.profile, name='profile'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/signup', views.signup, name='signup'),
    path('accounts/logout', views.signout, name='signout'),
    # path('post/new', include('problems.views'), name='problem_new')
]

problems/urls.py
from django.urls import path

from . import views

app_name = 'problems'
urlpatterns = [# ex: /polls/
    path('<str:order_by>/<int:order>/', views.problems_list, name='problems_list'),
    # path('', views.problems_list, name='problems_list'),
    # ex: /polls/5/
    path('<int:problem_id>/', views.problem, name='problem'), # ex: /polls/5/results/
    path('<int:problem_id>/solution/', views.view_solution, name='view_solution'),

    path('<int:problem_id>/delete/', views.delete_problem, name='delete_problem'), # new
    path('<int:problem_id>/edit/', views.edit_problem, name='edit_problem'), # new
    path('new/', views.problem_new, name='problem_new'),

    path('authors/', views.authors_list, name='authors_list'),

    path('authors/<int:author_id>', views.view_author, name='view_author'),

    path('themes/', views.themes_list, name='themes_list'),
    path('themes/<int:theme_id>', views.theme_view, name='theme_view'),

    path('events/', views.events_list, name='events_list'),

    path('events/<int:event_id>', views.event, name='event'),

    # path('search/', views.search, name='search'),

    path('<int:problem_id>/add_rating/', views.add_rating, name='add_rating'),
    path('<int:problem_id>/reduce_rating/', views.reduce_rating, name='reduce_rating'),
    path('<int:problem_id>/download/', views.download_problem, name='download_problem'),
    path('search/', views.search, name='search'),

    path('game/<int:game_id>', views.ugame, name='game'),
    path('start_game/', views.start_game, name='start_game'),
    path('end_game/<int:result>', views.end_game, name='end_game'),
    path('continue_game/<int:playerid>', views.get_player_game, name='continue_game')
]

problems/models.py
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator
from django.contrib.auth.models import User
from django.utils import timezone


class Problem(models.Model):
    title = models.CharField(default='', max_length=50, blank=True)
    text = models.TextField(default='')  # unique=True)
    complexity = models.IntegerField(default=0)
    solution = models.TextField(default='')
    year = models.IntegerField(default=0)
    max_level = models.IntegerField(default=1,
                                    validators=[MaxValueValidator(11), MinValueValidator(1)])
    min_level = models.IntegerField(default=1,
                                    validators=[MaxValueValidator(11), MinValueValidator(1)])
    is_solved = models.BooleanField(default=False)
    liked_users = models.ManyToManyField(User, blank=True)
    rating = models.IntegerField(default=0)

    def __str__(self):
        return '{} ({})'.format(str(self.title), str(self.id))


DEFAULT_IMAGE = '/problems/static/problems/placeholder.jpg'


class Author(models.Model):
    problems = models.ManyToManyField(Problem, blank=True)
    name = models.CharField(max_length=50, default='')
    description = models.TextField(default='', blank=True)
    photo = models.ImageField(default=DEFAULT_IMAGE, blank=True)

    def __str__(self):
        return str(self.name)


class Theme(models.Model):
    problems = models.ManyToManyField(Problem, blank=True)
    name = models.CharField(max_length=50, default='')
    description = models.TextField(default='', blank=True)

    def __str__(self):
        return '{} ({})'.format(str(self.name), str(self.id))


class Event(models.Model):
    problems = models.ManyToManyField(Problem, blank=True)
    name = models.CharField(max_length=50, default='')
    description = models.TextField(default='', blank=True)

    def __str__(self):
        return '{}'.format(str(self.name))


class Comment(models.Model):
    author = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    author_name = models.CharField(max_length=50, default='')
    problem = models.ForeignKey(Problem, on_delete=models.CASCADE, null=True)
    date = models.DateTimeField(default=timezone.now)
    text = models.TextField(default='')

    def __str__(self):
        return '{} {}'.format(self.author.username, str(self.date))


class Game(models.Model):
    player_id = models.IntegerField(default=-1)
    current_constellation = models.CharField(max_length=50, default='')
    target_constellation = models.CharField(max_length=50, default='')
    path = models.TextField(default='')
    error = models.TextField(default='Всё ок!')

    def __str__(self):
        return '{}'.format(str(self.id))

problems/forms.py
from django import forms

from .models import Problem, Author


class ProblemForm(forms.Form):
    title = forms.CharField(required=False, initial='', max_length=100, label='Название',
                            label_suffix='::')
    text = forms.CharField(required=True, widget=forms.Textarea)
    complexity = forms.IntegerField(initial=0)
    solution = forms.CharField(required=True, widget=forms.Textarea)
    # AUTHORS = [(author.id, author.name) for author in Author.objects.order_by('name')]
    AUTHORS = ([(0, 'Да'), (1, 'Нет')])
    existing_authors = forms.MultipleChoiceField(required=False, choices=AUTHORS,
                                                 widget=forms.CheckboxSelectMultiple)
    authors = forms.CharField(widget=forms.Textarea)

    THEMES = ([('Астрофизика', 'Астрофизика'),
               ('Оптика', 'Оптика'),
               ('Небесная сфера', 'Небесная сфера'),
               ('Небесная механика', 'Небесная механика'),
               ('Геометрия', 'Геометрия'),
               ('Время', 'Время'),
               ('Космология', 'Космология')])
    themes = forms.MultipleChoiceField(required=True, choices=THEMES,
                                       widget=forms.CheckboxSelectMultiple)

    year = forms.IntegerField(initial=0, required=False)
    event_name = forms.CharField(initial='', required=False)


class ConfirmDeleteForm(forms.Form):
    CHOICES = ([(True, 'Да'), (False, 'Нет')])
    is_confirmed = forms.ChoiceField(required=True, choices=CHOICES,
                                     widget=forms.RadioSelect(attrs={'class': 'Radio'}),
                                     initial=False)


class AuthorSearchForm(forms.Form):
    name = forms.CharField(required=True, initial='', max_length=100)

problems/views.py
from django.shortcuts import get_object_or_404, render, redirect
from django.db.models import Count
from django.db.utils import OperationalError
from django.core.exceptions import ObjectDoesNotExist
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.core.files import File
from datetime import datetime



from .models import Problem, Author, Event, Theme, Comment, Game
from .forms import ProblemForm, ConfirmDeleteForm, AuthorSearchForm
from ugol_game.ugol_game import UgolGame
from ugol_game.constellation_graph import csv_to_constellation_graph


MAX_COUNT = 100


def problems_list(request, order_by, order=0, problems=Problem.objects, flag=False):
    try:
        order = int(order)
        if order == 0:
            problems_list_ = problems.order_by(order_by)  # Problem.objects.order_by('theme)
        else:
            problems_list_ = problems.order_by(order_by).reverse()
        order ^= 1
        paginator = Paginator(problems_list_.all(), 20)
        page = request.GET.get('page')
        problems = paginator.get_page(page)
        context = {'problems': problems, 'order_by': order_by, 'order': order, 'user': request.user}
        if flag:
            return render(request, 'problems/problem_list.html', context)
        return render(request, 'problems/problem_list_all.html', context)
    except OperationalError:
        pass


def authors_list(request):
    try:
        form = AuthorSearchForm()
        authors_list_ = Author.objects.annotate(count=Count('problems')).order_by('-count')
        if request.method == 'POST':
            form = AuthorSearchForm(request.POST)
            if form.is_valid():
                authors_list_ = Author.objects.filter(
                    name__contains=form.cleaned_data['name']).annotate(
                    count=Count('problems')).order_by('-count')
        problem_count = [len(author.problems.all()) for author in authors_list_]
        context = {'authors_list': authors_list_, 'problem_count': problem_count, 'form': form}
        return render(request, 'problems/authors_list.html', context)  # return render
    except OperationalError:
        pass


def themes_list(request):
    try:
        themes_list_ = Theme.objects.annotate(count=Count('problems')).order_by('-count')
        problem_count = [len(author.problems.all()) for author in themes_list_]
        context = {'themes_list': themes_list_, 'problem_count': problem_count}
        return render(request, 'problems/themes_list.html', context)
    except OperationalError:
        pass


def theme_view(request, theme_id):
    try:
        theme_ = get_object_or_404(Theme, pk=theme_id)
        return problems_list(request, 'id', 0, theme_.problems, True)
    except OperationalError:
        pass


def problem(request, problem_id):
    try:
        problem_ = get_object_or_404(Problem, pk=problem_id)
        authors = problem_.author_set.all()
        themes = problem_.theme_set.all()

        events = problem_.event_set.all()
        problem_.text = parseToHtml(problem_.text)
        problem_.solution = parseToHtml(problem_.solution)
        problem_.save()

        context = {
            'problem': problem_, 'authors': authors, 'themes': themes, 'events': events,
            'user': request.user
        }
        return render(request, 'problems/problem.html', context)
    except OperationalError:
        pass


def add_rating(request, problem_id):
    problem_ = Problem.objects.get(pk=problem_id)
    voted_users = list(problem_.liked_users.all().values('id'))
    if request.user.id is not None and {'id': request.user.id} not in voted_users:
        problem_.liked_users.add(request.user)
        problem_.rating += 1
        problem_.save()
    return redirect('/problems/{}'.format(problem_id))


def reduce_rating(request, problem_id):
    problem_ = Problem.objects.get(pk=problem_id)
    voted_users = list(problem_.liked_users.all().values('id'))
    if request.user.id is not None and {'id': request.user.id} not in voted_users:
        problem_.liked_users.add(request.user)
        problem_.rating -= 1
        problem_.save()
    return redirect('/problems/{}'.format(problem_id))


def download_problem(request, problem_id):
    some_file = open('problems/static/problems/latex/tex_template.tex', "r")
    django_file = File(some_file)
    return render(request, 'problems/problem.html', {'download_file': django_file})


def event(request, event_id):
    try:
        event_ = get_object_or_404(Event, pk=event_id)
        return problems_list(request, 'id', 0, event_.problems, True)
    except OperationalError:
        pass


def view_solution(request, problem_id):
    try:
        problem_ = get_object_or_404(Problem, pk=problem_id)

        if request.method == 'POST':
            comment = Comment(text=request.POST.get('comment'), author=request.user,
                              problem=problem_)
            comment.save()
            return redirect('/problems/{}/solution/'.format(problem_.id))

        return render(request, 'problems/solution.html', {
            'problem': problem_, 'comments': problem_.comment_set.all(), 'user': request.user
        })
    except OperationalError:
        pass


def parseToHtml(string):
    string = string.replace('\r\n\r\n', '</p><p>').replace('~', '&nbsp;').replace('---', '&mdash;').replace('\r\n', ' ').replace('\par', '</p><p>').replace('\\\\', '</p><p>')
    if string[:3] == '<p>':
        return string
    return '<p>{}</p>'.format(string)


def problem_new(request):
    if request.method == 'POST':

        problem_ = Problem(title=request.POST.get('title'),
                           complexity=int(request.POST.get('complexity')),
                           text=parseToHtml(request.POST.get('text')),
                           solution=parseToHtml(request.POST.get('solution')),
                           year=int(request.POST.get('year')),
                           min_level=int(request.POST.get('min_level')),
                           max_level=int(request.POST.get('max_level')))

        problem_.save()

        for theme in Theme.objects.order_by('id'):
            if request.POST.get('theme_{}'.format(theme.id)):
                theme.problems.add(problem_)

        for i in range(MAX_COUNT):
            event_name = request.POST.get('event_name{}'.format(i))
            if not event_name:
                break
            try:
                event = Event.objects.get(name=event_name)
            except ObjectDoesNotExist:
                event = Event(name=event_name)
                event.save()
            event.problems.add(problem_)

        for i in range(MAX_COUNT):
            print('author_name{}'.format(i))
            author_name = request.POST.get('author_name{}'.format(i))
            if not author_name:
                print(author_name)
                break
            try:
                author = Author.objects.get(name=author_name)
            except ObjectDoesNotExist:
                author = Author(name=author_name)
                author.save()
            print(author.id)
            author.problems.add(problem_)
        return redirect('/problems/{}'.format(problem_.id))

    context = {
        'author_list': Author.objects.order_by('name'),
        'theme_list': Theme.objects.order_by('name'), 'years': [2019 - i for i in range(100)],
        'complexity': [1, 2, 3, 4, 5],
    }
    return render(request, 'problems/new_problem.html', context)


def delete_problem(request, problem_id):
    try:
        if request.method == 'POST':
            form = ConfirmDeleteForm(request.POST)
            if form.is_valid():
                problem_ = get_object_or_404(Problem, pk=problem_id)
                if str(form.cleaned_data['is_confirmed']) == 'True':
                    problem_.delete()
                    return redirect('/problems')
                else:
                    return redirect('/problems/{}'.format(problem_.id))
        else:
            form = ConfirmDeleteForm()
        return render(request, 'problems/delete_problem.html', {'form': form})
    except OperationalError:
        print('OperationalError')
        pass


def view_author(request, author_id):
    try:
        author = get_object_or_404(Author, pk=author_id)
        return problems_list(request, 'id', 0, author.problems, True)
    except OperationalError:
        pass


def events_list(request):
    try:
        events_list_ = Event.objects.annotate(count=Count('problems')).order_by('-count')
        problem_count = [len(event.problems.all()) for event in events_list_]
        context = {'events': events_list_, 'problem_count': problem_count}
        return render(request, 'problems/events.html', context)
    except OperationalError:
        pass


def edit_problem(request, problem_id):
    try:
        problem_ = Problem.objects.get(pk=problem_id)
        if request.method == 'POST':

            problem_.title = request.POST.get("title")
            problem_.complexity = request.POST.get("complexity")
            problem_.text = request.POST.get("text")
            problem_.solution = request.POST.get("solution")
            problem_.year = request.POST.get("year")

            problem_.save()

            try:
                event = Event.objects.get(name=request.POST.get('event_name'))
            except ObjectDoesNotExist:
                event = Event(name=request.POST.get('event_name'))
                event.save()
            event.problems.add(problem_)
            event.save()

            for theme in Theme.objects.order_by('id'):
                if request.POST.get('theme_{}'.format(theme.id)):
                    theme.problems.add(problem_)

            for author in Author.objects.order_by('id'):
                if request.POST.get('theme_{}'.format(author.id)):
                    author.problems.add(problem_)

            for ind in range(10):
                try:

problems/templates/problems/problem.html
{% extends 'base.html' %}
{% block content %}
    {% load problems_extras %}

    <style>
        textarea {
            border: none;
            border-bottom: 2px solid gray;
            width: 100%;
            height: 100px;
            background-color: #EEE;
            resize: none;
            overflow: hidden;
            padding: 8px;
        }

        textarea:focus {
            outline: none;
            border-bottom: 2px solid black;
            background-color: #F7F7F7;

        }

        .w3-padding-8 {
            padding: 8px 0;
        }
    </style>



    <div class="w3-row gradient-bg" style="height: calc(59px + 5vh);"></div>
    <div class="w3-row gradient-bg" style="min-height: calc(100vh - 110px - 125px);">
        <div class="w3-col l2 m1 s1"><p></p></div>
        <div class="w3-col l8 m10 s10">
            <div class="w3-xxlarge" style="color: white; padding: 0 0 32px 0; width: 100%">
                {% if problem.title %}
                    Задача &laquo;{{ problem.title }}&raquo;
                {% else %}
                    Задача #{{ problem.id }}
                {% endif %}
            </div>
            <div class="w3-light-gray w3-card" style="width: 100%; padding: 32px">
                <div class="w3-padding-8">
                    <b>Тематика:</b>
                    {% for theme in themes %}
                        {% if not forloop.last %}
                            {{ theme.name }},
                        {% else %}
                            {{ theme.name }}
                        {% endif %}
                    {% endfor %}
                </div>
                <div class="w3-padding-8">
                    <b>Авторство:</b>
                    {% for author in authors %}
                        <a href="{% url 'problems:view_author' author.id %}">
                            {% if not forloop.last %}
                                {{ author.name }},
                            {% else %}
                                {{ author.name }}
                            {% endif %}
                        </a>
                    {% endfor %}
                </div>
                <div class="w3-padding-8">
                    <b>Источники:</b>
                    {% for event in events %}
                        {{ event.name }}{% if not forloop.last %}, {% endif %}
                    {% endfor %}
                </div>
                <div class="w3-padding-8">
                    <b>Год:</b>
                    {{ problem.year }}
                </div>
                <div class="w3-padding-8">
                    <b>Класс:</b>
                    {{ problem.min_level }}
                    {% if problem.min_level < problem.max_level %}
                        &ndash; {{ problem.max_level }}
                    {% endif %}
                </div>
                <div class="w3-padding-8">
                    <b>Рейтинг:</b>&emsp;
                    <a href="{% url 'problems:reduce_rating' problem.id %}">
                        <i class="far fa-arrow-alt-circle-down"></i>
                    </a>
                    &ensp;{{ problem.rating }}&ensp;
                    <a href="{% url 'problems:add_rating' problem.id %}">
                        <i class="far fa-arrow-alt-circle-up"></i>
                    </a>
                </div>

                <div class="w3-padding-8">
                    {{ problem.text|safe }}
                </div>

                <div class="w3-padding-8" style="display: flex; flex-wrap: wrap">
                    {% if problem.solution != '' %}
                        <div class="w3-padding-8" style="flex-grow: 0; padding-right: 16px;">
                            <a href="{% url 'problems:view_solution' problem.id %}">
                                <button class="w3-button w3-black w3-hover-gray">
                                    Показать решение
                                </button>
                            </a>
                        </div>
                    {% endif %}
                    {#                    <div style="flex-grow: 0">#}
                    {#                        <a href="file:///problems/static/problems/latex/tex_template.tex">#}
                    {#                            <button class="w3-button w3-black w3-hover-gray">#}
                    {#                                Скачать в .tex#}
                    {#                            </button>#}
                    {#                        </a>#}
                    {#                    </div>#}
                    <div style="flex-grow: 1"></div>
                    {% if user.is_staff %}
                        <div class="w3-padding-8" style="flex-grow: 0; display: flex">
                            <div style="padding-right: 16px; flex-grow: 0">
                                <a href="{% url 'problems:delete_problem' problem.id %}">
                                    <button class="w3-button w3-black w3-hover-gray">
                                        Удалить задачу
                                    </button>
                                </a>
                            </div>
                            <div style="flex-grow: 0">
                                <a href="{% url 'problems:edit_problem' problem.id %}">
                                    <button class="w3-button w3-black w3-hover-gray">
                                        Редактировать задачу
                                    </button>
                                </a>
                            </div>
                        </div>
                    {% endif %}
                </div>
            </div>
        </div>
        <div class="w3-col l2 m1 s1"><p></p></div>
    </div>
    <div class="w3-row gradient-bg" style="height: calc(59px + 5vh);"></div>
{% endblock %}

problems/templates/problems/problem_list_all.html
{% extends 'base.html' %}
{% block content %}
    {% load static %}
    {% load problems_extras %}

    <link href="{% static 'problems/css/polyfill.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'problems/css/input.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'problems/css/table.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'problems/css/arrow.css' %}" rel="stylesheet" type="text/css">

    <header class="w3-display-container" id="home"
            style="width: 100vw; height: calc(100vh); z-index: 1">
        <div class="w3-display-left w3-text-white" style="padding: 80px 0 0 48px">
            <span class="w3-jumbo w3-hide-small"> Задачи </span><br>
            <span class="w3-xxlarge w3-hide-large w3-hide-medium">Задачи</span><br>
            <span class="w3-xlarge">Поставленная цель, которую стремятся достигнуть</span>
            <p>

                {% if user.is_authenticated %}
                    <a class="w3-inline" href="{% url 'problems:problem_new' %}">
                        <button class="w3-button w3-white w3-padding-large w3-large w3-margin-top w3-opacity w3-hover-opacity-off">
                            Добавить задачу
                        </button>
                    </a>
                {% else %}
                    <button style="opacity: 100%;"
                            class="w3-button w3-padding-large w3-large w3-margin-to">
                        &nbsp;
                    </button>
                {% endif %}
            </p>
        </div>
        <div id="arrow-down" style="z-index: -1">
            <i class="fa fa-chevron-down w3-opacity"
               style="font-size: 80px; color: #eeeeee"></i>
        </div>
    </header>

    <div class="w3-row gradient-bg" style="height: calc(59px + 5vh);"></div>
    <div id="content" class="gradient-bg w3-small" style="min-height: calc(100vh - 15vh); padding: 0 5vw;">
        <div class="w3-container w3-card-4 w3-gray w3-opacity-min"
             style="padding: 0; ">
            <a href="{% url 'problems:problems_list' 'id' order %}#content">
                <div class="w3-col l1 m1 s1 w3-border-top w3-border-left w3-border-bottom w3-padding-8 w3-center">
                    <b><i class="fab fa-slack-hash"></i></b>&nbsp;
                    {% if order_by == 'id' and order == 1 %}
                        <i class="fas fa-sort-amount-up w3-hide-medium w3-hide-small"></i>
                    {% elif order_by == 'id' and order == 0 %}
                        <i class="fas fa-sort-amount-down w3-hide-medium w3-hide-small"></i>
                    {% endif %}
                </div>
            </a>
            <a href="{% url 'problems:problems_list' 'event__name' order %}#content">
                <div class="w3-col l2 m4 s4 w3-center  w3-border-top w3-border-left w3-border-bottom w3-padding-8">
                    Источники
                    {% if order_by == 'event__name' and order == 1 %}
                        <i class="fas fa-sort-amount-up"></i>
                    {% elif order_by == 'event__name' and order == 0 %}
                        <i class="fas fa-sort-amount-down"></i>
                    {% endif %}
                </div>
            </a>
            <a href="{% url 'problems:problems_list' 'year' order %}#content">
                <div class="w3-col l1 m2 s2 w3-center w3-border-top w3-border-left w3-border-bottom w3-padding-8">
                    Год&nbsp;
                    {% if order_by == 'year' and order == 1 %}
                        <i class="fas fa-sort-amount-up"></i>
                    {% elif order_by == 'year' and order == 0 %}
                        <i class="fas fa-sort-amount-down"></i>
                    {% endif %}
                </div>
            </a>
            <a href="{% url 'problems:problems_list' 'theme__name' order %}#content">
                <div class="w3-col l3 m5 s5 w3-center  w3-border-top w3-border-left w3-border-bottom w3-padding-8">
                    Темы&nbsp;
                    {% if order_by == 'theme__name' and order == 1 %}
                        <i class="fas fa-sort-amount-up"></i>
                    {% elif order_by == 'theme__name' and order == 0 %}
                        <i class="fas fa-sort-amount-down"></i>
                    {% endif %}
                </div>
            </a>
            <a href="{% url 'problems:problems_list' 'complexity' order %}#content">
                <div class="w3-col l1 w3-hide-medium w3-hide-small w3-border-top w3-border-left w3-border-bottom w3-center w3-padding-8">
                    {{ "Сложность"|cut_string:7 }}&nbsp;
                    {% if order_by == 'complexity' and order == 1 %}
                        <i class="fas fa-sort-amount-up"></i>
                    {% elif order_by == 'complexity' and order == 0 %}
                        <i class="fas fa-sort-amount-down"></i>
                    {% endif %}
                </div>
            </a>
            <a href="{% url 'problems:problems_list' 'author__name' order %}#content">
                <div class="w3-col l3 w3-hide-medium w3-hide-small  w3-center w3-border-top w3-border-left w3-border-bottom w3-padding-8">
                    Авторы&nbsp;
                    {% if order_by == 'author__name' and order == 1 %}
                        <i class="fas fa-sort-amount-up"></i>
                    {% elif order_by == 'author__name' and order == 0 %}
                        <i class="fas fa-sort-amount-down"></i>
                    {% endif %}
                </div>
            </a>
            <a href="{% url 'problems:problems_list' 'rating' order %}#content">
                <div class="w3-col l1 w3-hide-medium w3-hide-small w3-center w3-border w3-padding-8">
                    Рейтинг&nbsp;
                    {% if order_by == 'rating' and order == 1 %}
                        <i class="fas fa-sort-amount-up"></i>
                    {% elif order_by == 'rating' and order == 0 %}
                        <i class="fas fa-sort-amount-down"></i>
                    {% endif %}
                </div>
            </a>
        </div>


        {% if problems %}
            {% for problem in problems %}
                <a href="{% url 'problems:problem' problem.id %}">
                    <div class="w3-container w3-white w3-opacity-min"
                         style="padding: 0;">
                        <div class="w3-col l1 m1 s1 w3-border-left w3-border-bottom w3-padding-8 w3-center">
                            <b>
                                {{ problem.id }}
                            </b>
                        </div>

                        <div class="w3-col l2 m4 s4 w3-border-left w3-border-bottom w3-center w3-padding-8">
                            {{ problem.event_set.all|authors_to_string:"15" }}
                        </div>
                        <div class="w3-col l1 m2 s2 w3-border-left w3-border-bottom w3-center w3-padding-8">
                            {{ problem.year }}
                        </div>
                        <div class="w3-col l3 m5 s5 w3-border-left w3-border-bottom w3-center w3-padding-8">
                            {{ problem.theme_set.all|authors_to_string:"20" }}
                        </div>
                        <div class="w3-col l1 w3-hide-medium w3-hide-small w3-border-left w3-border-bottom w3-center w3-padding-8">
                            {{ problem.complexity }}
                        </div>
                        <div class="w3-col l3 w3-hide-medium w3-hide-small w3-border-left w3-border-bottom w3-center w3-padding-8">
                            {{ problem.author_set.all|authors_to_string:"45" }}
                        </div>
                        <div class="w3-col l1 w3-hide-medium w3-hide-small  w3-border-left w3-border-bottom w3-center w3-padding-8">
                            {{ problem.rating }}
                        </div>
                    </div>
                </a>
            {% endfor %}
        {% else %}
            <p>No problems are available.</p>
        {% endif %}
        <div class="pagination w3-center w3-padding-8 w3-large" style="color: white;">
        <span class="step-links">
            <div style="display: inline">
                {% if problems.has_previous %}
                    <a href="?page={{ problems.previous_page_number }}#content" class="w3-button"
                       style="text-decoration: none">
                        <i class="fas fa-arrow-left"></i>
                    </a>
                {% endif %}
            </div>

            <span class="current">
                <b>{{ problems.number }}</b>
            </span>
            {% if problems.has_next %}
                <a href="?page={{ problems.next_page_number }}#content" class="w3-button"
                   style="text-decoration: none">
                    <i class="fas fa-arrow-right"></i>
                </a>
            {% endif %}
        </span>
        </div>
    </div>
{% endblock %}