astro_task_store/urls.py
from django.contrib import admin
from django.urls import path, include

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('admin/', admin.site.urls),
    path('problems/', include('problems.urls')),
    path('command/', views.command),
    path('profile/', views.profile, name='profile'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/signup', views.signup, name='signup'),
    path('accounts/logout', views.signout, name='signout'),
    # path('post/new', include('problems.views'), name='problem_new')
]

problems/urls.py
from django.urls import path

from . import views

app_name = 'problems'
urlpatterns = [# ex: /polls/
    path('<str:order_by>/<int:order>/', views.problems_list, name='problems_list'),
    # path('', views.problems_list, name='problems_list'),
    # ex: /polls/5/
    path('<int:problem_id>/', views.problem, name='problem'), # ex: /polls/5/results/
    path('<int:problem_id>/solution/', views.view_solution, name='view_solution'),

    path('<int:problem_id>/delete/', views.delete_problem, name='delete_problem'), # new
    path('<int:problem_id>/edit/', views.edit_problem, name='edit_problem'), # new
    path('new/', views.problem_new, name='problem_new'),

    path('authors/', views.authors_list, name='authors_list'),

    path('authors/<int:author_id>', views.view_author, name='view_author'),

    path('themes/', views.themes_list, name='themes_list'),
    path('themes/<int:theme_id>', views.theme_view, name='theme_view'),

    path('events/', views.events_list, name='events_list'),

    path('events/<int:event_id>', views.event, name='event'),

    # path('search/', views.search, name='search'),

    path('<int:problem_id>/add_rating/', views.add_rating, name='add_rating'),
    path('<int:problem_id>/reduce_rating/', views.reduce_rating, name='reduce_rating'),
    path('<int:problem_id>/download/', views.download_problem, name='download_problem'),
    path('search/', views.search, name='search'),

    path('game/<int:game_id>', views.ugame, name='game'),
    path('start_game/', views.start_game, name='start_game'),
    path('end_game/<int:result>', views.end_game, name='end_game'),
    path('continue_game/<int:playerid>', views.get_player_game, name='continue_game')
]

problems/models.py
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator
from django.contrib.auth.models import User
from django.utils import timezone


class Problem(models.Model):
    title = models.CharField(default='', max_length=50, blank=True)
    text = models.TextField(default='')  # unique=True)
    complexity = models.IntegerField(default=0)
    solution = models.TextField(default='')
    year = models.IntegerField(default=0)
    max_level = models.IntegerField(default=1,
                                    validators=[MaxValueValidator(11), MinValueValidator(1)])
    min_level = models.IntegerField(default=1,
                                    validators=[MaxValueValidator(11), MinValueValidator(1)])
    is_solved = models.BooleanField(default=False)
    liked_users = models.ManyToManyField(User, blank=True)
    rating = models.IntegerField(default=0)

    def __str__(self):
        return '{} ({})'.format(str(self.title), str(self.id))


DEFAULT_IMAGE = '/problems/static/problems/placeholder.jpg'


class Author(models.Model):
    problems = models.ManyToManyField(Problem, blank=True)
    name = models.CharField(max_length=50, default='')
    description = models.TextField(default='', blank=True)
    photo = models.ImageField(default=DEFAULT_IMAGE, blank=True)

    def __str__(self):
        return str(self.name)


class Theme(models.Model):
    problems = models.ManyToManyField(Problem, blank=True)
    name = models.CharField(max_length=50, default='')
    description = models.TextField(default='', blank=True)

    def __str__(self):
        return '{} ({})'.format(str(self.name), str(self.id))


class Event(models.Model):
    problems = models.ManyToManyField(Problem, blank=True)
    name = models.CharField(max_length=50, default='')
    description = models.TextField(default='', blank=True)

    def __str__(self):
        return '{}'.format(str(self.name))


class Comment(models.Model):
    author = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    author_name = models.CharField(max_length=50, default='')
    problem = models.ForeignKey(Problem, on_delete=models.CASCADE, null=True)
    date = models.DateTimeField(default=timezone.now)
    text = models.TextField(default='')

    def __str__(self):
        return '{} {}'.format(self.author.username, str(self.date))


class Game(models.Model):
    player_id = models.IntegerField(default=-1)
    current_constellation = models.CharField(max_length=50, default='')
    target_constellation = models.CharField(max_length=50, default='')
    path = models.TextField(default='')
    error = models.TextField(default='Всё ок!')

    def __str__(self):
        return '{}'.format(str(self.id))

problems/forms.py
from django import forms

from .models import Problem, Author


class ProblemForm(forms.Form):
    title = forms.CharField(required=False, initial='', max_length=100, label='Название',
                            label_suffix='::')
    text = forms.CharField(required=True, widget=forms.Textarea)
    complexity = forms.IntegerField(initial=0)
    solution = forms.CharField(required=True, widget=forms.Textarea)
    # AUTHORS = [(author.id, author.name) for author in Author.objects.order_by('name')]
    AUTHORS = ([(0, 'Да'), (1, 'Нет')])
    existing_authors = forms.MultipleChoiceField(required=False, choices=AUTHORS,
                                                 widget=forms.CheckboxSelectMultiple)
    authors = forms.CharField(widget=forms.Textarea)

    THEMES = ([('Астрофизика', 'Астрофизика'),
               ('Оптика', 'Оптика'),
               ('Небесная сфера', 'Небесная сфера'),
               ('Небесная механика', 'Небесная механика'),
               ('Геометрия', 'Геометрия'),
               ('Время', 'Время'),
               ('Космология', 'Космология')])
    themes = forms.MultipleChoiceField(required=True, choices=THEMES,
                                       widget=forms.CheckboxSelectMultiple)

    year = forms.IntegerField(initial=0, required=False)
    event_name = forms.CharField(initial='', required=False)


class ConfirmDeleteForm(forms.Form):
    CHOICES = ([(True, 'Да'), (False, 'Нет')])
    is_confirmed = forms.ChoiceField(required=True, choices=CHOICES,
                                     widget=forms.RadioSelect(attrs={'class': 'Radio'}),
                                     initial=False)


class AuthorSearchForm(forms.Form):
    name = forms.CharField(required=True, initial='', max_length=100)

problems/views.py
from django.shortcuts import get_object_or_404, render, redirect
from django.db.models import Count
from django.db.utils import OperationalError
from django.core.exceptions import ObjectDoesNotExist
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.core.files import File
from datetime import datetime



from .models import Problem, Author, Event, Theme, Comment, Game
from .forms import ProblemForm, ConfirmDeleteForm, AuthorSearchForm
from ugol_game.ugol_game import UgolGame
from ugol_game.constellation_graph import csv_to_constellation_graph


MAX_COUNT = 100


def problems_list(request, order_by, order=0, problems=Problem.objects, flag=False):
    try:
        order = int(order)
        if order == 0:
            problems_list_ = problems.order_by(order_by)  # Problem.objects.order_by('theme)
        else:
            problems_list_ = problems.order_by(order_by).reverse()
        order ^= 1
        paginator = Paginator(problems_list_.all(), 20)
        page = request.GET.get('page')
        problems = paginator.get_page(page)
        context = {'problems': problems, 'order_by': order_by, 'order': order, 'user': request.user}
        if flag:
            return render(request, 'problems/problem_list.html', context)
        return render(request, 'problems/problem_list_all.html', context)
    except OperationalError:
        pass


def authors_list(request):
    try:
        form = AuthorSearchForm()
        authors_list_ = Author.objects.annotate(count=Count('problems')).order_by('-count')
        if request.method == 'POST':
            form = AuthorSearchForm(request.POST)
            if form.is_valid():
                authors_list_ = Author.objects.filter(
                    name__contains=form.cleaned_data['name']).annotate(
                    count=Count('problems')).order_by('-count')
        problem_count = [len(author.problems.all()) for author in authors_list_]
        context = {'authors_list': authors_list_, 'problem_count': problem_count, 'form': form}
        return render(request, 'problems/authors_list.html', context)  # return render
    except OperationalError:
        pass


def themes_list(request):
    try:
        themes_list_ = Theme.objects.annotate(count=Count('problems')).order_by('-count')
        problem_count = [len(author.problems.all()) for author in themes_list_]
        context = {'themes_list': themes_list_, 'problem_count': problem_count}
        return render(request, 'problems/themes_list.html', context)
    except OperationalError:
        pass


def theme_view(request, theme_id):
    try:
        theme_ = get_object_or_404(Theme, pk=theme_id)
        return problems_list(request, 'id', 0, theme_.problems, True)
    except OperationalError:
        pass


def problem(request, problem_id):
    try:
        problem_ = get_object_or_404(Problem, pk=problem_id)
        authors = problem_.author_set.all()
        themes = problem_.theme_set.all()

        events = problem_.event_set.all()
        problem_.text = parseToHtml(problem_.text)
        problem_.solution = parseToHtml(problem_.solution)
        problem_.save()

        context = {
            'problem': problem_, 'authors': authors, 'themes': themes, 'events': events,
            'user': request.user
        }
        return render(request, 'problems/problem.html', context)
    except OperationalError:
        pass


def add_rating(request, problem_id):
    problem_ = Problem.objects.get(pk=problem_id)
    voted_users = list(problem_.liked_users.all().values('id'))
    if request.user.id is not None and {'id': request.user.id} not in voted_users:
        problem_.liked_users.add(request.user)
        problem_.rating += 1
        problem_.save()
    return redirect('/problems/{}'.format(problem_id))


def reduce_rating(request, problem_id):
    problem_ = Problem.objects.get(pk=problem_id)
    voted_users = list(problem_.liked_users.all().values('id'))
    if request.user.id is not None and {'id': request.user.id} not in voted_users:
        problem_.liked_users.add(request.user)
        problem_.rating -= 1
        problem_.save()
    return redirect('/problems/{}'.format(problem_id))


def download_problem(request, problem_id):
    some_file = open('problems/static/problems/latex/tex_template.tex', "r")
    django_file = File(some_file)
    return render(request, 'problems/problem.html', {'download_file': django_file})


def event(request, event_id):
    try:
        event_ = get_object_or_404(Event, pk=event_id)
        return problems_list(request, 'id', 0, event_.problems, True)
    except OperationalError:
        pass


def view_solution(request, problem_id):
    try:
        problem_ = get_object_or_404(Problem, pk=problem_id)

        if request.method == 'POST':
            comment = Comment(text=request.POST.get('comment'), author=request.user,
                              problem=problem_)
            comment.save()
            return redirect('/problems/{}/solution/'.format(problem_.id))

        return render(request, 'problems/solution.html', {
            'problem': problem_, 'comments': problem_.comment_set.all(), 'user': request.user
        })
    except OperationalError:
        pass


def parseToHtml(string):
    string = string.replace('\r\n\r\n', '</p><p>').replace('~', '&nbsp;').replace('---', '&mdash;').replace('\r\n', ' ').replace('\par', '</p><p>').replace('\\\\', '</p><p>')
    if string[:3] == '<p>':
        return string
    return '<p>{}</p>'.format(string)


def problem_new(request):
    if request.method == 'POST':

        problem_ = Problem(title=request.POST.get('title'),
                           complexity=int(request.POST.get('complexity')),
                           text=parseToHtml(request.POST.get('text')),
                           solution=parseToHtml(request.POST.get('solution')),
                           year=int(request.POST.get('year')),
                           min_level=int(request.POST.get('min_level')),
                           max_level=int(request.POST.get('max_level')))

        problem_.save()

        for theme in Theme.objects.order_by('id'):
            if request.POST.get('theme_{}'.format(theme.id)):
                theme.problems.add(problem_)

        for i in range(MAX_COUNT):
            event_name = request.POST.get('event_name{}'.format(i))
            if not event_name:
                break
            try:
                event = Event.objects.get(name=event_name)
            except ObjectDoesNotExist:
                event = Event(name=event_name)
                event.save()
            event.problems.add(problem_)

        for i in range(MAX_COUNT):
            print('author_name{}'.format(i))
            author_name = request.POST.get('author_name{}'.format(i))
            if not author_name:
                print(author_name)
                break
            try:
                author = Author.objects.get(name=author_name)
            except ObjectDoesNotExist:
                author = Author(name=author_name)
                author.save()
            print(author.id)
            author.problems.add(problem_)
        return redirect('/problems/{}'.format(problem_.id))

    context = {
        'author_list': Author.objects.order_by('name'),
        'theme_list': Theme.objects.order_by('name'), 'years': [2019 - i for i in range(100)],
        'complexity': [1, 2, 3, 4, 5],
    }
    return render(request, 'problems/new_problem.html', context)


def delete_problem(request, problem_id):
    try:
        if request.method == 'POST':
            form = ConfirmDeleteForm(request.POST)
            if form.is_valid():
                problem_ = get_object_or_404(Problem, pk=problem_id)
                if str(form.cleaned_data['is_confirmed']) == 'True':
                    problem_.delete()
                    return redirect('/problems')
                else:
                    return redirect('/problems/{}'.format(problem_.id))
        else:
            form = ConfirmDeleteForm()
        return render(request, 'problems/delete_problem.html', {'form': form})
    except OperationalError:
        print('OperationalError')
        pass


def view_author(request, author_id):
    try:
        author = get_object_or_404(Author, pk=author_id)
        return problems_list(request, 'id', 0, author.problems, True)
    except OperationalError:
        pass


def events_list(request):
    try:
        events_list_ = Event.objects.annotate(count=Count('problems')).order_by('-count')
        problem_count = [len(event.problems.all()) for event in events_list_]
        context = {'events': events_list_, 'problem_count': problem_count}
        return render(request, 'problems/events.html', context)
    except OperationalError:
        pass


def edit_problem(request, problem_id):
    try:
        problem_ = Problem.objects.get(pk=problem_id)
        if request.method == 'POST':

            problem_.title = request.POST.get("title")
            problem_.complexity = request.POST.get("complexity")
            problem_.text = request.POST.get("text")
            problem_.solution = request.POST.get("solution")
            problem_.year = request.POST.get("year")

            problem_.save()

            try:
                event = Event.objects.get(name=request.POST.get('event_name'))
            except ObjectDoesNotExist:
                event = Event(name=request.POST.get('event_name'))
                event.save()
            event.problems.add(problem_)
            event.save()

            for theme in Theme.objects.order_by('id'):
                if request.POST.get('theme_{}'.format(theme.id)):
                    theme.problems.add(problem_)

            for author in Author.objects.order_by('id'):
                if request.POST.get('theme_{}'.format(author.id)):
                    author.problems.add(problem_)

            for ind in range(10):
                try:

templates/base.html
<!DOCTYPE html>
<html>
<head>
    <title>Задачи по астрономии</title>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <meta name="google-site-verification" content="Zq253QEGhnMypugAQrK9NXzhzIfAi_HflpKUn989jzk"/>
    {% load static %}
    <link href="https://fonts.googleapis.com/css?family=Montserrat:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i&amp;subset=cyrillic-ext"
          rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Annie+Use+Your+Telescope|Open+Sans"
          rel="stylesheet">

    <link href="https://fonts.googleapis.com/css?family=Gloria+Hallelujah" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Cedarville+Cursive" rel="stylesheet">
    {#    <!-- MUI -->#}
    <link href="https://cdn.muicss.com/mui-0.9.41/css/mui.min.css" rel="stylesheet"
          type="text/css"/>
    <script src="https://cdn.muicss.com/mui-0.9.41/js/mui.min.js"></script>


    <!-- Compiled and minified CSS -->
    {#    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.css">#}

    <!-- Compiled and minified JavaScript -->
    {#    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.js"></script>#}


    {#    <link rel="stylesheet" type="text/css" href="semantic/dist/semantic.min.css">#}
    {#    <script#}
    {#            src="https://code.jquery.com/jquery-3.1.1.min.js"#}
    {#            integrity="sha256-hVVnYaiADRTO2PzUGmuLJr8BLUSjGIZsDYGmIJLv2b8="#}
    {#            crossorigin="anonymous"></script>#}
    {#    <script src="semantic/dist/semantic.min.js"></script>#}

    <!-- W3-shchool -->
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">

    <!-- Project style -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">

    <!-- Down-arrow on title pages -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/arrow.css' %}">

    <!-- jQuery -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

    {#    <!-- Metro 4 -->#}
    {#    <link rel="stylesheet" href="https://cdn.metroui.org.ua/v4/css/metro-all.css">#}


    <!-- Font Awesome for icnos -->
    <link rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css"
          integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU"
          crossorigin="anonymous">

    <!-- MathJax -->
    <script src='https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-MML-AM_CHTML'
            async></script>
    <script type="text/x-mathjax-config">
        MathJax.Hub.Config({
            tex2jax: {
                inlineMath: [ ['$','$'], ["\\(","\\)"] ],
                processEscapes: true,
                webFont: "STIX"
            }
        });


    </script>
    <style>
        a {
            text-decoration: none;
        }
    </style>
</head>

<body class="my-style bgimg-1" style="padding-top: 0px">

<!-- Navbar (sit on top) -->
<nav class="w3-top" style="width:100%;overflow:hidden; z-index: 2">
    <div class="w3-bar w3-black  w3-card" id="myNavbar">
        <a href="/" class="w3-bar-item"
           style="padding: 8px 16px; font-family: 'Gloria Hallelujah', cursive; font-weight: 100; font-size: x-large;  text-decoration: none;">
            astro-problems
        </a>
        <!-- Right-sided navbar links -->
        <div class="w3-right w3-hide-small w3-hide-medium">
            {#            <a href="index.html" class="w3-bar-item w3-button w3-padding-16">Главная</a>#}
            <a href="{% url 'problems:problems_list' 'id' 0 %}"
               class="w3-bar-item w3-button w3-padding-16"><i class="fab fa-wpexplorer"></i> Задачи</a>
            <a href="{% url 'problems:authors_list' %}" class="w3-bar-item w3-button w3-padding-16"><i
                    class="far fa-user"></i> Авторы</a>
            <a href="{% url 'problems:themes_list' %}"
               class="w3-bar-item w3-button w3-padding-16"><i
                    class="far fa-compass"></i> Темы</a>
            <a href="{% url 'problems:events_list' %}"
               class="w3-bar-item w3-button w3-padding-16"><i class="fas fa-map-marker-alt"></i>
                Источники</a>
            <a href="{% url 'problems:start_game'%}"
               class="w3-bar-item w3-button w3-padding-16"><i class="fas fa-dice"></i>
                Играть</a>
            <a href="{% url 'problems:search' %}"
               class="w3-bar-item w3-button w3-padding-16"><i class="fa fa-search"></i>
                Поиск</a>
            {#            <a href="/command" class="w3-bar-item w3-button w3-padding-16"><i class="fas fa-users"></i>#}
            {#                Наша команда</a>#}
            {% if request.user.id %}
                <a href="{% url 'profile' %}"
                   class="w3-bar-item w3-button w3-padding-16"><b>{{ request.user }}</b></a>
            {% else %}
                <a href="{% url 'login' %}" class="w3-bar-item w3-button w3-padding-16"><i
                        class="fas fa-sign-in-alt"></i>
                    Войти</a>
            {% endif %}

        </div>
        <!-- Hide right-floated links on small screens and replace them with a menu icon -->

        <a href="javascript:void(0)"
           class="w3-bar-item w3-button w3-right w3-hide-large" onclick="w3_open()">
            <i class="fa fa-bars"></i>
        </a>
    </div>
</nav>

<!-- Sidebar on small screens when clicking the menu icon -->
<nav class="w3-sidebar w3-bar-block w3-black w3-card w3-animate-left w3-hide-large"
     style="display:none; z-index: 10" id="mySidebar">
    {% if request.user.id %}
        <a onclick="w3_close()" href="{% url 'profile' %}"
           class="w3-bar-item w3-button w3-padding-16"><b>{{ request.user }}</b></a>
    {% else %}
        <a onclick="w3_close()" href="{% url 'login' %}"
           class="w3-bar-item w3-button w3-padding-16"><i
                class="fas fa-sign-in-alt"></i>
            Войти</a>
    {% endif %}
    <a onclick="w3_close()" href="{% url 'problems:problems_list' 'id' 0 %}"
       class="w3-bar-item w3-button w3-padding-16"><i class="fab fa-wpexplorer"></i> Задачи</a>
    <a onclick="w3_close()" href="{% url 'problems:authors_list' %}"
       class="w3-bar-item w3-button w3-padding-16"><i
            class="far fa-user"></i> Авторы</a>
    <a onclick="w3_close()" href="{% url 'problems:themes_list' %}"
       class="w3-bar-item w3-button w3-padding-16"><i
            class="far fa-compass"></i> Темы</a>
    <a onclick="w3_close()" href="{% url 'problems:events_list' %}"
       class="w3-bar-item w3-button w3-padding-16"><i class="fas fa-map-marker-alt"></i>
        Источники</a>
    <a onclick="w3_close()" href="{% url 'problems:search' %}"
       class="w3-bar-item w3-button w3-padding-16"><i class="fa fa-search"></i>
        Поиск</a>
    <a href="javascript:void(0)" onclick="w3_close()"
       class="w3-bar-item w3-button w3-padding-16"><i class="fas fa-times"></i> Закрыть</a>
</nav>


{% block content %}

{% endblock %}


<!-- Footer -->
{#<div style="width: 100%; height: 8vh; z-index: -1;"></div>#}
<footer class="w3-center w3-normal w3-black "
        style="width: 100%; z-index: 2; padding: 8px 0 8px 0;">
    <p class="w3-opacity" style="margin: 0">&copy;Астрономический кружок им Е.П. Левитана, 2018&nbsp;&ndash;&nbsp;&infin; </p>
</footer>

<script>
    // Modal Image Gallery
    function onClick(element) {
        document.getElementById("img01").src = element.src;
        document.getElementById("modal01").style.display = "block";
        var captionText = document.getElementById("caption");
        captionText.innerHTML = element.alt;
    }


    // Toggle between showing and hiding the sidebar when clicking the menu icon
    var mySidebar = document.getElementById("mySidebar");

    function w3_open() {
        if (mySidebar.style.display === 'block') {
            mySidebar.style.display = 'none';
        } else {
            mySidebar.style.display = 'block';
        }
    }

    // Close the sidebar with the close button
    function w3_close() {
        mySidebar.style.display = "none";
    }
</script>

</body>
</html>

templates/command.html
{% extends 'base.html' %}
{% block content %}

    <!-- Header with full-height image -->
    <header class="bgimg-1 w3-display-container" id="home" style="width: 100vw; height: 100vh">
        <div class="w3-display-left w3-text-white" style="padding:48px">
            <span class="w3-jumbo w3-hide-small">Решай задачи с нами</span><br>
            <span class="w3-xxlarge w3-hide-large w3-hide-medium">Решай задачи с нами</span><br>
            <span class="w3-xlarge">Это проще, чем кажется.</span>
            <p><a href="#about"
                  class="w3-button w3-white w3-padding-large w3-large w3-margin-top w3-opacity w3-hover-opacity-off">Далее</a>
            </p>
        </div>
        <div class="w3-display-bottomleft w3-text-grey w3-large" style="padding:24px 48px">
            <i class="fab fa-vk w3-hover-opacity"></i>
            <i class="fas fa-globe w3-hover-opacity"></i>
        </div>

        <div class="arrow-down w3-display-bottom w3-opacity"></div>
    </header>

    <!-- Team Section -->
    {% load static %}
    <div class="w3-container w3-light-grey" style="padding:128px 16px" id="team">
        <p class="w3-center w3-xxlarge">НАША КОМАНДА</p>
        {#    <p class="w3-center w3-large">Это мы</p>#}
        <div class="w3-row-padding w3-center" style="margin-top:64px">
            <div class="w3-col l2 m2"><p></p></div>
            <div class="w3-col l4 m8 w3-margin-bottom">
                <div class="w3-card">
                    <img class="" src="{% static 'problems/img/ashepelev.jpg' %}"
                         style="width:100%">
                    <div class="w3-container">
                        <p class="w3-large">Алексей Шепелев</p>
                        <p class="w3-opacity">CEO & Founder</p>
                        <p>
                            Троекратный победитель финала всероссийской олимпиады школьников по
                            астрономии. Дважды серебряный призер международной астрономической
                            олимпиады. <br> Студент ФИВТ МФТИ.
                        </p>
                        <p>
                            <a href="https://vk.com/alexeyshepelevv" style="text-decoration: none"
                               target="_blank">
                                <button class="w3-button w3-light-grey w3-block"><i
                                        class="fa fa-envelope"></i> Contact
                                </button>
                            </a>
                        </p>
                    </div>
                </div>
            </div>
            <div class="w3-col l4 m6 w3-margin-bottom">
                <div class="w3-card">
                    <img class="" src="{% static 'problems/img/ddolgov.jpg' %}" style="width:100%">
                    <div class="w3-container">
                        <p class="w3-large">Долгов Даниил</p>
                        <p class="w3-opacity">Art Director</p>
                        <p>Троекратный победитель финала всероссийской олимпиады школьников по
                            астрономии. Обладатель трёх золотых медалей международной олимпиады по
                            астрономии и астрофизике. <br> Студент ФИВТ МФТИ.</p>
                        <p>
                            <a href="https://vk.com/eeedadol" style="text-decoration: none"
                               target="_blank">
                                <button class="w3-button w3-light-grey w3-block"><i
                                        class="fa fa-envelope"></i> Contact
                                </button>
                            </a>
                        </p>
                    </div>
                </div>
            </div>
            <div class="w3-col l2 m2"><p></p></div>
        </div>
    </div>
{% endblock %}